name: Checkup
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  expo-ios-build:
    name: Build Expo ios app
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
        working-directory: expo-flutter

      - name: Build Flutter iOS artifacts
        run: npm run flutter:build:ios
        working-directory: expo-flutter

      - name: Install Cocoapods dependencies
        working-directory: expo-flutter/ios
        run: pod install

      - name: Build Expo iOS app
        working-directory: expo-flutter/ios
        run: |
          xcodebuild archive -workspace ExpoFlutter.xcworkspace \
          -scheme ExpoFlutter \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          -archivePath archive/ExpoFlutter.xcarchive \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
